In [2]:
# Pandas Reference Sheet
import pandas as pd
import numpy as np

# import the dataset
data = pd.read_csv("cars.csv")

In [3]:
# Copy the dataset
data_copy = data.copy()

In [4]:
# Sort values
# can specify multiple values to sort by
data_copy.sort_values(by="Popularity", ascending=False)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
8361,Ford,Ranger,2011,regular unleaded,207.0,6.0,MANUAL,four wheel drive,4.0,NaN,Compact,Extended Cab Pickup,19,15,5657,26070
5041,Ford,Fusion,2017,regular unleaded,231.0,4.0,AUTOMATIC,all wheel drive,4.0,Performance,Midsize,Sedan,29,20,5657,27405
5031,Ford,Fusion,2015,regular unleaded,231.0,4.0,AUTOMATIC,all wheel drive,4.0,Performance,Midsize,Sedan,31,22,5657,32780
5032,Ford,Fusion,2015,regular unleaded,175.0,4.0,AUTOMATIC,front wheel drive,4.0,NaN,Midsize,Sedan,34,22,5657,24035
5033,Ford,Fusion,2015,regular unleaded,231.0,4.0,AUTOMATIC,front wheel drive,4.0,Performance,Midsize,Sedan,33,22,5657,30780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5202,Genesis,G80,2017,regular unleaded,311.0,6.0,AUTOMATIC,rear wheel drive,4.0,"Luxury,Performance",Large,Sedan,28,18,21,41400
5203,Genesis,G80,2017,premium unleaded (recommended),420.0,8.0,AUTOMATIC,rear wheel drive,4.0,"Luxury,High-Performance",Large,Sedan,23,15,21,54550
2118,Spyker,C8,2009,premium unleaded (required),400.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,18,13,2,209990
2117,Spyker,C8,2009,premium unleaded (required),400.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,18,13,2,219990
2116,Spyker,C8,2009,premium unleaded (required),400.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,18,13,2,209990

In [5]:
# see first/last values of a dataset, can pass through a number for number of rows
data_copy.head(10)
data_copy.tail(10)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
11904,BMW,Z8,2002,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,130000
11905,BMW,Z8,2003,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,131500
11906,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46020
11907,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56570
11908,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50520
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [6]:
# find number of rows in a data set
len(data_copy)

11914

In [7]:
# shape of a data set (number of rows and columns)
data_copy.shape

(11914, 16)

In [8]:
# gets the data types of each column
data_copy.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [97]:
# Get counts the data types
data_copy.dtypes.value_counts()

object     8
float64    4
int64      4
dtype: int64

In [9]:
# extract a row from a data set
# returns a Series, a single column of values
# can be accessed by index or by index label
data_copy.iloc[50]

Make                                                   BMW
Model                                             2 Series
Year                                                  2017
Engine Fuel Type            premium unleaded (recommended)
Engine HP                                              335
Engine Cylinders                                         6
Transmission Type                                AUTOMATIC
Driven_Wheels                              all wheel drive
Number of Doors                                          2
Market Category      Factory Tuner,Luxury,High-Performance
Vehicle Size                                       Compact
Vehicle Style                                        Coupe
highway MPG                                             31
city mpg                                                21
Popularity                                            3916
MSRP                                                 46450
Name: 50, dtype: object

In [10]:
# access a column value by dot or bracket notation
data_copy.Make
data_copy["Make"]

0            BMW
1            BMW
2            BMW
3            BMW
4            BMW
          ...
11909      Acura
11910      Acura
11911      Acura
11912      Acura
11913    Lincoln
Name: Make, Length: 11914, dtype: object

In [11]:
# can filter a value by criteria
# can also be assigned to a variable
data_copy[data_copy["Make"] == "BMW"].head()
is_car_a_bmw = data_copy["Make"] == "BMW"
is_car_two_door = data_copy["Number of Doors"] == 2.0

In [12]:
data_copy[is_car_a_bmw]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11901,BMW,Z4,2016,premium unleaded (required),240.0,4.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,34,22,3916,49700
11902,BMW,Z4,2016,premium unleaded (required),335.0,6.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,24,17,3916,66350
11903,BMW,Z8,2001,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,128000
11904,BMW,Z8,2002,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,130000
11905,BMW,Z8,2003,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,131500

In [13]:
# can filter by and (&) conditions as well as either (|)
data_copy[is_car_a_bmw | is_car_two_door]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11901,BMW,Z4,2016,premium unleaded (required),240.0,4.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,34,22,3916,49700
11902,BMW,Z4,2016,premium unleaded (required),335.0,6.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,24,17,3916,66350
11903,BMW,Z8,2001,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,128000
11904,BMW,Z8,2002,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,130000
11905,BMW,Z8,2003,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,131500

In [14]:
# can use arithmetic operators
data_copy["Year"]< 2011

0        False
1        False
2        False
3        False
4        False
         ...
11909    False
11910    False
11911    False
11912    False
11913     True
Name: Year, Length: 11914, dtype: bool

In [15]:
# specify a range of values
year_range = data_copy["Year"].between(2003, 2011)

In [16]:
data_copy[year_range]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11905,BMW,Z8,2003,premium unleaded (required),394.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Convertible,19,12,3916,131500
11906,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46020
11907,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56570
11908,Acura,ZDX,2011,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50520
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [17]:
# replace column text
# can also be used to replace all values in a column by specifying the column name
data_copy.columns = data_copy.columns.str.replace(" ", "_").str.lower()

In [18]:
# can convert values to other dtypes with astype
data_copy["year"] = data_copy["year"].astype(float)
data_copy.dtypes

make                  object
model                 object
year                 float64
engine_fuel_type      object
engine_hp            float64
engine_cylinders     float64
transmission_type     object
driven_wheels         object
number_of_doors      float64
market_category       object
vehicle_size          object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
popularity             int64
msrp                   int64
dtype: object

In [19]:
# get the mean value
data_copy.number_of_doors.mean()

3.4360933825999327

In [20]:
# group certain values together
popular_cars = data_copy.groupby("make")

In [21]:
# create a Series object
guitar_brands = ["SG", "Prestige", "Idol", "Stratocaster"]
labels =["Gibson", "Ibanez", "Wasburn", "Fender"]

In [22]:
pd.Series(guitar_brands, labels)

Gibson               SG
Ibanez         Prestige
Wasburn            Idol
Fender     Stratocaster
dtype: object

In [23]:
# can also create a Series from a dictionary
guitars_with_makers = {"Gibson": "SG", "Ibanez": "Prestige", "Washburn":"Idol", "Fender": "Stratocaster"}

In [24]:
guitar_series = pd.Series(guitars_with_makers)

In [25]:
# count the number of values in a series
guitar_series.size

4

In [26]:
# check the values of a series
guitar_series.values

array(['SG', 'Prestige', 'Idol', 'Stratocaster'], dtype=object)

In [27]:
# check the index/labels of a series
guitar_series.index

Index(['Gibson', 'Ibanez', 'Washburn', 'Fender'], dtype='object')

In [28]:
# returns the dimensions of a panda data structure
guitar_series.shape

(4,)

In [29]:
# returns whether all data values are unique
guitar_series.is_unique

True

In [30]:
# returns whether all values are increasing
guitar_series.is_monotonic

False

In [31]:
# can accept a tuple as a source as well
guitar_second_series = pd.Series(("Gibson", "Ibanez", "Fender"))

In [32]:
guitar_second_series

0    Gibson
1    Ibanez
2    Fender
dtype: object

In [33]:
# sets will need to be transformed before being passed to the constructor

In [34]:
# Series also accepts an ndarray as data
random_series = pd.Series(np.random.randint(1, 100, 10))

In [35]:
random_series

0    30
1    77
2    90
3    53
4    34
5    35
6    72
7    43
8    86
9     2
dtype: int64

In [36]:
# add up values in a Series
random_series.sum()
random_series.sum(skipna = False)

522

In [37]:
# sets the minimum number of non-null values that must be present for the Series to be calculated
random_series.sum(min_count = 3)

522

In [38]:
random_series.product()

6982432069536000

In [39]:
# can pass a skipna boolean value to add up to the first null
random_series.cumsum()
random_series.cumsum(skipna=False)

0     30
1    107
2    197
3    250
4    284
5    319
6    391
7    434
8    520
9    522
dtype: int64

In [40]:
# calculates percentage change between elements of a series
# can specify parameters for backfill/forward fill
random_series.pct_change()

0         NaN
1    1.566667
2    0.168831
3   -0.411111
4   -0.358491
5    0.029412
6    1.057143
7   -0.402778
8    1.000000
9   -0.976744
dtype: float64

In [41]:
# Average
random_series.mean()

52.2

In [42]:
# Middle value
random_series.median()

48.0

In [43]:
# Standard deviation of the value, statistical measure of the amount of variation
random_series.std()

28.487034087653125

In [44]:
# Max and Min, can also return string values
random_series.max()
random_series.min()

2

In [45]:
first_three_letters = pd.Series(["a", "b", "c"])

In [46]:
first_three_letters.min()

'a'

In [47]:
first_three_letters.max()

'c'

In [48]:
# returns a lot of useful info about a Series
random_series.describe()

count    10.000000
mean     52.200000
std      28.487034
min       2.000000
25%      34.250000
50%      48.000000
75%      75.750000
max      90.000000
dtype: float64

In [49]:
# random sample of values from a series
random_series.sample(3)

0    30
8    86
1    77
dtype: int64

In [50]:
# number of unique values
random_series.nunique()

10

In [51]:
# perform an arithmetical operation on each member of a Series
random_series + 1

0    31
1    78
2    91
3    54
4    35
5    36
6    73
7    44
8    87
9     3
dtype: int64

In [52]:
(random_series + 1).sum()

532

In [53]:
# can also add different Series together - test_series1 + test_series2

In [54]:
# Trying to combine two differently shaped Series will result in NaN if an index can't be matched - see "broadcasting"

In [55]:
# Series can also be passed to Python's builtins
len(random_series)

10

In [56]:
random_series[0]

30

In [57]:
type(random_series)

pandas.core.series.Series

In [58]:
# returns the methods attached to the Series object
dir(random_series)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_binop',
 '_box_item_values',
 '_builtin_table',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_convert_dtypes',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_find_valid_index',
 '_from_axes',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_iget_item_cache',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_map_values',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_ndarray_values',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_name',
 '_set_subtyp',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_setup_axes',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_series_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'bool',
 'clip',
 'combine',
 'combine_first',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'interpolate',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'iteritems',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [59]:
# returns Series values as a list
list(random_series)

[30, 77, 90, 53, 34, 35, 72, 43, 86, 2]

In [60]:
max(random_series)

90

In [61]:
min(random_series)

2

In [62]:
96 in list(random_series)

False

In [63]:
type(random_series)

pandas.core.series.Series

In [64]:
# determines whether a series has null values
random_series.hasnans

False

In [65]:
data_copy["make"].hasnans

False

In [66]:
# can parse dates upon reading - pd.read_csv("filename.csv", index_col = "Date", parse_dates = ["Date"], squeeze = True)

In [67]:
# sort a series
# null values will be displayed at the end by default
data_copy["make"].sort_values(ascending=False)

8924    Volvo
8923    Volvo
8930    Volvo
8929    Volvo
8928    Volvo
        ...
5932    Acura
5931    Acura
5930    Acura
5929    Acura
8540    Acura
Name: make, Length: 11914, dtype: object

In [68]:
# get rid of null values
data_copy.dropna()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,BMW,1 Series M,2011.0,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011.0,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011.0,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011.0,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011.0,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012.0,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012.0,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012.0,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013.0,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006.0,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [69]:
# sort index - data_copy.sort_index(ascending = False, na_position = "first")

In [70]:
# returns the largest values
random_series.nlargest(5)

2    90
8    86
1    77
6    72
3    53
dtype: int64

In [71]:
# returns the smallest values
random_series.nsmallest(5)

9     2
0    30
4    34
5    35
7    43
dtype: int64

In [72]:
# inplace parameter mutates the original object, defaults to False
random_series.sort_values(inplace=True)

In [73]:
random_series.head()

9     2
0    30
4    34
5    35
7    43
dtype: int64

In [74]:
# returns unique values of a Series
random_series.value_counts()

30    1
77    1
43    1
90    1
72    1
34    1
86    1
53    1
35    1
2     1
dtype: int64

In [75]:
data_copy["make"].value_counts(ascending=True)

Spyker              3
Genesis             3
Bugatti             3
Alfa Romeo          5
McLaren             5
Maybach            16
HUMMER             17
Tesla              18
Lotus              29
Rolls-Royce        31
Lamborghini        52
Maserati           58
Scion              60
FIAT               62
Ferrari            69
Bentley            74
Plymouth           82
Aston Martin       93
Saab              111
Porsche           136
Land Rover        143
Oldsmobile        150
Lincoln           164
Pontiac           186
Chrysler          187
Buick             196
Lexus             202
Mitsubishi        213
Kia               231
Acura             252
Subaru            256
Volvo             281
Hyundai           303
Audi              328
Infiniti          330
BMW               334
Suzuki            351
Mercedes-Benz     353
Cadillac          397
Mazda             423
Honda             449
GMC               515
Nissan            558
Dodge             626
Toyota            746
Volkswagen        809
Ford              881
Chevrolet        1123
Name: make, dtype: int64

In [76]:
# return the frequencies of unique values
(data_copy.make.value_counts(normalize=True) * 100).round(2)

Chevrolet        9.43
Ford             7.39
Volkswagen       6.79
Toyota           6.26
Dodge            5.25
Nissan           4.68
GMC              4.32
Honda            3.77
Mazda            3.55
Cadillac         3.33
Mercedes-Benz    2.96
Suzuki           2.95
BMW              2.80
Infiniti         2.77
Audi             2.75
Hyundai          2.54
Volvo            2.36
Subaru           2.15
Acura            2.12
Kia              1.94
Mitsubishi       1.79
Lexus            1.70
Buick            1.65
Chrysler         1.57
Pontiac          1.56
Lincoln          1.38
Oldsmobile       1.26
Land Rover       1.20
Porsche          1.14
Saab             0.93
Aston Martin     0.78
Plymouth         0.69
Bentley          0.62
Ferrari          0.58
FIAT             0.52
Scion            0.50
Maserati         0.49
Lamborghini      0.44
Rolls-Royce      0.26
Lotus            0.24
Tesla            0.15
HUMMER           0.14
Maybach          0.13
McLaren          0.04
Alfa Romeo       0.04
Bugatti          0.03
Genesis          0.03
Spyker           0.03
Name: make, dtype: float64

In [78]:
# sort the values into bins
# values are inclusive on the bottom, less than or equal on the top
bins = [0, 50, 100, 200, 300, 400]
random_series.value_counts(bins=bins)

(50.0, 100.0]     5
(-0.001, 50.0]    5
(300.0, 400.0]    0
(200.0, 300.0]    0
(100.0, 200.0]    0
dtype: int64

In [80]:
# A DataFrame is a grid or table
# Like a Series, a DataFrame can be created from diverse data formats 
# Create a DataFrame from a Dictionary
city_data = {
"City": ["New York City", "Paris", "Barcelona", "Rome"], "Country": ["United States", "France", "Spain", "Italy"], "Population": [8600000, 2141000, 5515000, 2873000]
}
df_city = pd.DataFrame(city_data)

In [81]:
df_city

            City        Country  Population
0  New York City  United States     8600000
1          Paris         France     2141000
2      Barcelona          Spain     5515000
3           Rome          Italy     2873000

In [83]:
# Use the .transpose() or .T method to transpose a DataFrame
transposed_city = df_city.T
transposed_city

                        0        1          2        3
City        New York City    Paris  Barcelona     Rome
Country     United States   France      Spain    Italy
Population        8600000  2141000    5515000  2873000

In [87]:
into_the_pipe=np.random.randint(5, 6, [5,5])
into_the_pipe

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [91]:
index=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
columns=["One", "Two", "Three", "Four", "Five"]

In [92]:
weekly_readings = pd.DataFrame(into_the_pipe, index, columns)

In [94]:
weekly_readings

           One  Two  Three  Four  Five
Monday       5    5      5     5     5
Tuesday      5    5      5     5     5
Wednesday    5    5      5     5     5
Thursday     5    5      5     5     5
Friday       5    5      5     5     5

In [95]:
# Some values are imported as strings by default, we can change this with parameters
# Import column values as dates
# pd.read_csv("file.csv", parse_dates=["Column Name"])

In [98]:
# Describe the Index values
# (Output shows the index is numerical)
data_copy.index

RangeIndex(start=0, stop=11914, step=1)

In [101]:
# Show the contained values
data_copy.values

array([['BMW', '1 Series M', 2011.0, ..., 19, 3916, 46135],
       ['BMW', '1 Series', 2011.0, ..., 19, 3916, 40650],
       ['BMW', '1 Series', 2011.0, ..., 20, 3916, 36350],
       ...,
       ['Acura', 'ZDX', 2012.0, ..., 16, 204, 50620],
       ['Acura', 'ZDX', 2013.0, ..., 16, 204, 50920],
       ['Lincoln', 'Zephyr', 2006.0, ..., 17, 61, 28995]], dtype=object)

In [109]:
weekly_readings.index

Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], dtype='object')

In [108]:
weekly_readings.values

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [102]:
# Show both index and values
weekly_readings.axes

[Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], dtype='object'),
 Index(['One', 'Two', 'Three', 'Four', 'Five'], dtype='object')]

In [103]:
# Get the number of values in a DataFrame (rows * columns)
# Use .count() to exclude missing values
weekly_readings.size

25

In [106]:
data_copy.size

190624

In [107]:
data_copy.count()

make                 11914
model                11914
year                 11914
engine_fuel_type     11911
engine_hp            11845
engine_cylinders     11884
transmission_type    11914
driven_wheels        11914
number_of_doors      11908
market_category       8172
vehicle_size         11914
vehicle_style        11914
highway_mpg          11914
city_mpg             11914
popularity           11914
msrp                 11914
dtype: int64

In [110]:
# Get Head/Tail Values from DataFrame
data_copy.head(2)

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,BMW,1 Series M,2011.0,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011.0,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650

In [111]:
# Get Head/Tail Values from DataFrame
data_copy.tail(3)

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
11911,Acura,ZDX,2012.0,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013.0,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006.0,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [112]:
# Show a random sample
data_copy.sample(5)

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
8858,Volvo,S40,2010.0,premium unleaded (recommended),227.0,5.0,MANUAL,all wheel drive,4.0,Luxury,Compact,Sedan,27,20,870,31350
8891,Volvo,S60,2015.0,regular unleaded,240.0,4.0,AUTOMATIC,front wheel drive,4.0,"Luxury,Performance",Midsize,Sedan,37,25,870,33300
3005,Chevrolet,Corvette,2017.0,premium unleaded (recommended),455.0,8.0,MANUAL,rear wheel drive,2.0,High-Performance,Compact,Coupe,25,16,1385,59905
9059,Chrysler,Sebring,2009.0,regular unleaded,173.0,4.0,AUTOMATIC,front wheel drive,4.0,NaN,Midsize,Sedan,30,21,1013,25920
5654,Volkswagen,GTI,2013.0,premium unleaded (recommended),200.0,4.0,AUTOMATED_MANUAL,front wheel drive,2.0,"Hatchback,Performance",Compact,2dr Hatchback,33,24,873,31495

In [113]:
# Return unique values
data_copy.nunique()

make                   48
model                 915
year                   28
engine_fuel_type       10
engine_hp             356
engine_cylinders        9
transmission_type       5
driven_wheels           4
number_of_doors         3
market_category        71
vehicle_size            3
vehicle_style          16
highway_mpg            59
city_mpg               69
popularity             48
msrp                 6049
dtype: int64

In [114]:
# For DataFrame min/max, returns a Series of smallest/largest amounts for each column
data_copy.min()

make                            Acura
model                        1 Series
year                             1990
engine_hp                          55
engine_cylinders                    0
transmission_type    AUTOMATED_MANUAL
driven_wheels         all wheel drive
number_of_doors                     2
vehicle_size                  Compact
vehicle_style           2dr Hatchback
highway_mpg                        12
city_mpg                            7
popularity                          2
msrp                             2000
dtype: object

In [115]:
data_copy.max()

make                            Volvo
model                              xD
year                             2017
engine_hp                        1001
engine_cylinders                   16
transmission_type             UNKNOWN
driven_wheels        rear wheel drive
number_of_doors                     4
vehicle_size                  Midsize
vehicle_style                   Wagon
highway_mpg                       354
city_mpg                          137
popularity                       5657
msrp                          2065902
dtype: object

In [120]:
# Can pass a number and columns to nlargest() or nsmallest()
data_copy.nlargest(3, "year")

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
32,FIAT,124 Spider,2017.0,premium unleaded (recommended),160.0,4.0,MANUAL,rear wheel drive,2.0,Performance,Compact,Convertible,35,26,819,27495
33,FIAT,124 Spider,2017.0,premium unleaded (recommended),160.0,4.0,MANUAL,rear wheel drive,2.0,Performance,Compact,Convertible,35,26,819,24995
34,FIAT,124 Spider,2017.0,premium unleaded (recommended),160.0,4.0,MANUAL,rear wheel drive,2.0,Performance,Compact,Convertible,35,26,819,28195

In [121]:
data_copy.nsmallest(4, "highway_mpg")

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
598,Ferrari,550,2001.0,premium unleaded (required),485.0,12.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,12,8,2774,248500
599,Ferrari,550,2001.0,premium unleaded (required),485.0,12.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,12,8,2774,205840
3565,Lamborghini,Diablo,2001.0,premium unleaded (required),550.0,12.0,MANUAL,all wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,12,9,1158,294900
4024,Ferrari,Enzo,2003.0,premium unleaded (required),660.0,12.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,12,7,2774,643330

In [125]:
# Call sum on all columns in a DataFrame
data_copy.sum()

make                 BMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWBMWB...
model                1 Series M1 Series1 Series1 Series1 Series1 Se...
year                                                       2.39517e+07
engine_hp                                                  2.95398e+06
engine_cylinders                                                 66893
transmission_type    MANUALMANUALMANUALMANUALMANUALMANUALMANUALMANU...
driven_wheels        rear wheel driverear wheel driverear wheel dri...
number_of_doors                                                  40917
vehicle_size         CompactCompactCompactCompactCompactCompactComp...
vehicle_style        CoupeConvertibleCoupeCoupeConvertibleCoupeConv...
highway_mpg                                                     317359
city_mpg                                                        235102
popularity                                                    18525212
msrp                                                         483645697
dtype: object

In [126]:
data_copy["city_mpg"].sum()

235102

In [127]:
# Target only numeric columns, otherwise String values are concatenated
data_copy.sum(numeric_only=True)

year                 23951719.0
engine_hp             2953978.0
engine_cylinders        66893.0
number_of_doors         40917.0
highway_mpg            317359.0
city_mpg               235102.0
popularity           18525212.0
msrp                483645697.0
dtype: float64

In [128]:
# Average
data_copy.mean()

year                 2010.384338
engine_hp             249.386070
engine_cylinders        5.628829
number_of_doors         3.436093
highway_mpg            26.637485
city_mpg               19.733255
popularity           1554.911197
msrp                40594.737032
dtype: float64

In [132]:
# Middle value
data_copy.median()

year                 2015.0
engine_hp             227.0
engine_cylinders        6.0
number_of_doors         4.0
highway_mpg            26.0
city_mpg               18.0
popularity           1385.0
msrp                29995.0
dtype: float64

In [133]:
data_copy.sort_values("year")

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
9415,Mitsubishi,Sigma,1990.0,regular unleaded,142.0,6.0,AUTOMATIC,front wheel drive,4.0,NaN,Midsize,Sedan,20,16,436,2000
6514,Ford,LTD Crown Victoria,1990.0,regular unleaded,150.0,8.0,AUTOMATIC,rear wheel drive,4.0,NaN,Large,Wagon,22,15,5657,2000
6515,Ford,LTD Crown Victoria,1990.0,regular unleaded,150.0,8.0,AUTOMATIC,rear wheel drive,4.0,NaN,Large,Wagon,22,15,5657,2000
6516,Ford,LTD Crown Victoria,1990.0,regular unleaded,150.0,8.0,AUTOMATIC,rear wheel drive,4.0,NaN,Large,Wagon,22,15,5657,2000
6517,Ford,LTD Crown Victoria,1990.0,regular unleaded,150.0,8.0,AUTOMATIC,rear wheel drive,4.0,NaN,Large,Sedan,22,15,5657,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6490,Lexus,LS 460,2017.0,premium unleaded (required),386.0,8.0,AUTOMATIC,rear wheel drive,4.0,"Luxury,Performance",Large,Sedan,24,16,454,72520
6491,Lexus,LS 460,2017.0,premium unleaded (required),386.0,8.0,AUTOMATIC,rear wheel drive,4.0,"Luxury,Performance",Large,Sedan,24,16,454,78820
6492,Lexus,LS 460,2017.0,premium unleaded (required),359.0,8.0,AUTOMATIC,all wheel drive,4.0,"Luxury,Performance",Large,Sedan,23,16,454,75465
6344,Mitsubishi,Lancer,2017.0,regular unleaded,148.0,4.0,AUTOMATIC,front wheel drive,4.0,NaN,Compact,Sedan,34,27,436,18795
7391,Mitsubishi,Outlander,2017.0,premium unleaded (recommended),224.0,6.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,27,20,436,31695

In [134]:
data_copy.sort_values("engine_hp", ascending=False).head()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
11362,Bugatti,Veyron 16.4,2008.0,premium unleaded (required),1001.0,16.0,AUTOMATED_MANUAL,all wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,14,8,820,2065902
11363,Bugatti,Veyron 16.4,2008.0,premium unleaded (required),1001.0,16.0,AUTOMATED_MANUAL,all wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,14,8,820,1500000
11364,Bugatti,Veyron 16.4,2009.0,premium unleaded (required),1001.0,16.0,AUTOMATED_MANUAL,all wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,14,8,820,1705769
1630,Lamborghini,Aventador,2016.0,premium unleaded (required),750.0,12.0,AUTOMATED_MANUAL,all wheel drive,2.0,"Exotic,High-Performance",Midsize,Coupe,18,11,1158,490700
1629,Lamborghini,Aventador,2016.0,premium unleaded (required),750.0,12.0,AUTOMATED_MANUAL,all wheel drive,2.0,"Exotic,High-Performance",Midsize,Convertible,18,11,1158,535500

In [136]:
# Sort multiple columns
data_copy.sort_values(["make", "engine_hp"], ascending=True).head()

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
5796,Acura,ILX Hybrid,2014.0,premium unleaded (recommended),111.0,4.0,AUTOMATIC,front wheel drive,4.0,"Luxury,Hybrid",Compact,Sedan,38,39,204,28900
5797,Acura,ILX Hybrid,2014.0,premium unleaded (recommended),111.0,4.0,AUTOMATIC,front wheel drive,4.0,"Luxury,Hybrid",Compact,Sedan,38,39,204,34600
5918,Acura,Integra,1999.0,regular unleaded,140.0,4.0,MANUAL,front wheel drive,4.0,Luxury,Compact,Sedan,29,22,204,2827
5919,Acura,Integra,1999.0,regular unleaded,140.0,4.0,MANUAL,front wheel drive,4.0,Luxury,Compact,Sedan,29,22,204,3000
5920,Acura,Integra,1999.0,regular unleaded,140.0,4.0,MANUAL,front wheel drive,2.0,"Hatchback,Luxury",Compact,2dr Hatchback,29,22,204,2912

In [141]:
# Can also pass an array of booleans to the sort parameter to sort by multiple columns
sort_these=data_copy.sort_values(["engine_hp", "popularity"], ascending=[True, False])
sort_these[["engine_hp", "popularity"]]

      engine_hp  popularity
6794       55.0        1385
6798       55.0        1385
2528       62.0        2202
2533       62.0        2202
1469       63.0        5657
...         ...         ...
2908        NaN          61
6908        NaN          61
6910        NaN          61
6916        NaN          61
6918        NaN          61

[11914 rows x 2 columns]

In [142]:
# Similarly, we can sort by index values
data_copy.sort_index(ascending=False)

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
11913,Lincoln,Zephyr,2006.0,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995
11912,Acura,ZDX,2013.0,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11911,Acura,ZDX,2012.0,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11910,Acura,ZDX,2012.0,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11909,Acura,ZDX,2012.0,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,BMW,1 Series,2011.0,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
3,BMW,1 Series,2011.0,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
2,BMW,1 Series,2011.0,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
1,BMW,1 Series,2011.0,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
0,BMW,1 Series M,2011.0,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135

In [144]:
# Axes can be rows or columns and are the dimensions in which the DF can be sorted
data_copy.sort_index(axis="columns").head()

,city_mpg,driven_wheels,engine_cylinders,engine_fuel_type,engine_hp,highway_mpg,make,market_category,model,msrp,number_of_doors,popularity,transmission_type,vehicle_size,vehicle_style,year
0,19,rear wheel drive,6.0,premium unleaded (required),335.0,26,BMW,"Factory Tuner,Luxury,High-Performance",1 Series M,46135,2.0,3916,MANUAL,Compact,Coupe,2011.0
1,19,rear wheel drive,6.0,premium unleaded (required),300.0,28,BMW,"Luxury,Performance",1 Series,40650,2.0,3916,MANUAL,Compact,Convertible,2011.0
2,20,rear wheel drive,6.0,premium unleaded (required),300.0,28,BMW,"Luxury,High-Performance",1 Series,36350,2.0,3916,MANUAL,Compact,Coupe,2011.0
3,18,rear wheel drive,6.0,premium unleaded (required),230.0,28,BMW,"Luxury,Performance",1 Series,29450,2.0,3916,MANUAL,Compact,Coupe,2011.0
4,18,rear wheel drive,6.0,premium unleaded (required),230.0,28,BMW,Luxury,1 Series,34500,2.0,3916,MANUAL,Compact,Convertible,2011.0

In [146]:
data_copy.set_index("make").head(10)

,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
make,,,,,,,,,,,,,,,
BMW,1 Series M,2011.0,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
BMW,1 Series,2011.0,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
BMW,1 Series,2011.0,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
BMW,1 Series,2011.0,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
BMW,1 Series,2011.0,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
BMW,1 Series,2012.0,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,31200
BMW,1 Series,2012.0,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,26,17,3916,44100
BMW,1 Series,2012.0,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,39300
BMW,1 Series,2012.0,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,36900
BMW,1 Series,2013.0,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,27,18,3916,37200